import dayjs from 'dayjs';

export const dummyBuildingResources = [
  {
    type: 'building',
    id: 1,
    text: 'SCI (Sciences Building)',
    distance: null,
  },
];

export const dummyRoomResources = [
  {
    type: 'room',
    id: 1,
    text: '1.119',
    link: '',
    buildingId: 1,
  },
  {
    type: 'room',
    id: 2,
    text: '1.129',
    link: '',
    buildingId: 1,
  },
  {
    type: 'room',
    id: 3,
    text: '1.139',
    link: '',
    buildingId: 1,
  },
  {
    type: 'room',
    id: 4,
    text: '1.159',
    link: '',
    buildingId: 1,
  },
  {
    type: 'room',
    id: 5,
    text: '1.169',
    link: '',
    buildingId: 1,
  },
  {
    type: 'room',
    id: 6,
    text: '1.179',
    link: '',
    buildingId: 1,
  },
  {
    type: 'room',
    id: 7,
    text: '1.188',
    link: '',
    buildingId: 1,
  },
  {
    type: 'room',
    id: 8,
    text: '1.210',
    link: '',
    buildingId: 1,
  },
  {
    type: 'room',
    id: 9,
    text: '1.220',
    link: '',
    buildingId: 1,
  },
  {
    type: 'room',
    id: 10,
    text: '2.215',
    link: '',
    buildingId: 1,
  },
  {
    type: 'room',
    id: 11,
    text: '2.220',
    link: '',
    buildingId: 1,
  },
  {
    type: 'room',
    id: 12,
    text: '2.225',
    link: '',
    buildingId: 1,
  },
  {
    type: 'room',
    id: 13,
    text: '2.230',
    link: '',
    buildingId: 1,
  },
  {
    type: 'room',
    id: 14,
    text: '2.235',
    link: '',
    buildingId: 1,
  },
  {
    type: 'room',
    id: 15,
    text: '2.240',
    link: '',
    buildingId: 1,
  },
  {
    type: 'room',
    id: 16,
    text: '3.220',
    link: '',
    buildingId: 1,
  },
  {
    type: 'room',
    id: 17,
    text: '3.230',
    link: '',
    buildingId: 1,
  },
  {
    type: 'room',
    id: 18,
    text: '3.240',
    link: '',
    buildingId: 1,
  },
  {
    type: 'room',
    id: 19,
    text: '3.250',
    link: '',
    buildingId: 1,
  },
  {
    type: 'room',
    id: 20,
    text: '3.260',
    link: '',
    buildingId: 1,
  },
  {
    type: 'room',
    id: 21,
    text: '3.270',
    link: '',
    buildingId: 1,
  },
];

export const dummyScheduleData = [
  {
    id: '1',
    Subject: 'Class',
    StartTime: dayjs('08:30', 'HH:mm').toDate(),
    EndTime: dayjs('09:45', 'HH:mm').toDate(),
    roomId: 1,
    buildingId: 1,
  },
  {
    id: '2',
    Subject: 'Class',
    StartTime: dayjs('11:30', 'HH:mm').toDate(),
    EndTime: dayjs('12:45', 'HH:mm').toDate(),
    roomId: 1,
    buildingId: 1,
  },
  {
    id: '3',
    Subject: 'Class',
    StartTime: dayjs('13:00', 'HH:mm').toDate(),
    EndTime: dayjs('14:15', 'HH:mm').toDate(),
    roomId: 1,
    buildingId: 1,
  },
  {
    id: '4',
    Subject: 'Class',
    StartTime: dayjs('16:00', 'HH:mm').toDate(),
    EndTime: dayjs('17:15', 'HH:mm').toDate(),
    roomId: 1,
    buildingId: 1,
  },
  {
    id: '5',
    Subject: 'Class',
    StartTime: dayjs('10:00', 'HH:mm').toDate(),
    EndTime: dayjs('11:15', 'HH:mm').toDate(),
    roomId: 2,
    buildingId: 1,
  },
  {
    id: '6',
    Subject: 'Class',
    StartTime: dayjs('11:30', 'HH:mm').toDate(),
    EndTime: dayjs('12:45', 'HH:mm').toDate(),
    roomId: 2,
    buildingId: 1,
  },
  {
    id: '7',
    Subject: 'Class',
    StartTime: dayjs('19:00', 'HH:mm').toDate(),
    EndTime: dayjs('21:45', 'HH:mm').toDate(),
    roomId: 2,
    buildingId: 1,
  },
  {
    id: '8',
    Subject: 'Class',
    StartTime: dayjs('13:00', 'HH:mm').toDate(),
    EndTime: dayjs('14:15', 'HH:mm').toDate(),
    roomId: 3,
    buildingId: 1,
  },
  {
    id: '9',
    Subject: 'Class',
    StartTime: dayjs('17:30', 'HH:mm').toDate(),
    EndTime: dayjs('18:45', 'HH:mm').toDate(),
    roomId: 3,
    buildingId: 1,
  },
  {
    id: '10',
    Subject: 'Class',
    StartTime: dayjs('08:30', 'HH:mm').toDate(),
    EndTime: dayjs('9:45', 'HH:mm').toDate(),
    roomId: 4,
    buildingId: 1,
  },
  {
    id: '11',
    Subject: 'Class',
    StartTime: dayjs('13:00', 'HH:mm').toDate(),
    EndTime: dayjs('14:15', 'HH:mm').toDate(),
    roomId: 4,
    buildingId: 1,
  },
  {
    id: '12',
    Subject: 'Class',
    StartTime: dayjs('14:30', 'HH:mm').toDate(),
    EndTime: dayjs('15:45', 'HH:mm').toDate(),
    roomId: 4,
    buildingId: 1,
  },
  {
    id: '13',
    Subject: 'Class',
    StartTime: dayjs('11:30', 'HH:mm').toDate(),
    EndTime: dayjs('12:45', 'HH:mm').toDate(),
    roomId: 5,
    buildingId: 1,
  },
  {
    id: '14',
    Subject: 'Class',
    StartTime: dayjs('13:00', 'HH:mm').toDate(),
    EndTime: dayjs('14:15', 'HH:mm').toDate(),
    roomId: 5,
    buildingId: 1,
  },
  {
    id: '15',
    Subject: 'Class',
    StartTime: dayjs('17:30', 'HH:mm').toDate(),
    EndTime: dayjs('18:45', 'HH:mm').toDate(),
    roomId: 6,
    buildingId: 1,
  },
  {
    id: '16',
    Subject: 'Class',
    StartTime: dayjs('19:00', 'HH:mm').toDate(),
    EndTime: dayjs('21:45', 'HH:mm').toDate(),
    roomId: 6,
    buildingId: 1,
  },
  {
    id: '17',
    Subject: 'Class',
    StartTime: dayjs('08:30', 'HH:mm').toDate(),
    EndTime: dayjs('09:45', 'HH:mm').toDate(),
    roomId: 7,
    buildingId: 1,
  },
  {
    id: '18',
    Subject: 'Class',
    StartTime: dayjs('11:30', 'HH:mm').toDate(),
    EndTime: dayjs('12:45', 'HH:mm').toDate(),
    roomId: 7,
    buildingId: 1,
  },
  {
    id: '19',
    Subject: 'Class',
    StartTime: dayjs('14:30', 'HH:mm').toDate(),
    EndTime: dayjs('15:45', 'HH:mm').toDate(),
    roomId: 8,
    buildingId: 1,
  },
  {
    id: '1',
    Subject: 'Class',
    StartTime: dayjs('08:30', 'HH:mm').toDate(),
    EndTime: dayjs('09:45', 'HH:mm').toDate(),
    roomId: 9,
    buildingId: 1,
  },
  {
    id: '2',
    Subject: 'Class',
    StartTime: dayjs('11:30', 'HH:mm').toDate(),
    EndTime: dayjs('12:45', 'HH:mm').toDate(),
    roomId: 9,
    buildingId: 1,
  },
  {
    id: '3',
    Subject: 'Class',
    StartTime: dayjs('13:00', 'HH:mm').toDate(),
    EndTime: dayjs('14:15', 'HH:mm').toDate(),
    roomId: 9,
    buildingId: 1,
  },
  {
    id: '4',
    Subject: 'Class',
    StartTime: dayjs('16:00', 'HH:mm').toDate(),
    EndTime: dayjs('17:15', 'HH:mm').toDate(),
    roomId: 9,
    buildingId: 1,
  },
  {
    id: '5',
    Subject: 'Class',
    StartTime: dayjs('10:00', 'HH:mm').toDate(),
    EndTime: dayjs('11:15', 'HH:mm').toDate(),
    roomId: 10,
    buildingId: 1,
  },
  {
    id: '6',
    Subject: 'Class',
    StartTime: dayjs('11:30', 'HH:mm').toDate(),
    EndTime: dayjs('12:45', 'HH:mm').toDate(),
    roomId: 10,
    buildingId: 1,
  },
  {
    id: '7',
    Subject: 'Class',
    StartTime: dayjs('19:00', 'HH:mm').toDate(),
    EndTime: dayjs('21:45', 'HH:mm').toDate(),
    roomId: 10,
    buildingId: 1,
  },
  {
    id: '8',
    Subject: 'Class',
    StartTime: dayjs('13:00', 'HH:mm').toDate(),
    EndTime: dayjs('14:15', 'HH:mm').toDate(),
    roomId: 11,
    buildingId: 1,
  },
  {
    id: '9',
    Subject: 'Class',
    StartTime: dayjs('17:30', 'HH:mm').toDate(),
    EndTime: dayjs('18:45', 'HH:mm').toDate(),
    roomId: 11,
    buildingId: 1,
  },
  {
    id: '10',
    Subject: 'Class',
    StartTime: dayjs('08:30', 'HH:mm').toDate(),
    EndTime: dayjs('9:45', 'HH:mm').toDate(),
    roomId: 12,
    buildingId: 1,
  },
  {
    id: '11',
    Subject: 'Class',
    StartTime: dayjs('13:00', 'HH:mm').toDate(),
    EndTime: dayjs('14:15', 'HH:mm').toDate(),
    roomId: 12,
    buildingId: 1,
  },
  {
    id: '12',
    Subject: 'Class',
    StartTime: dayjs('14:30', 'HH:mm').toDate(),
    EndTime: dayjs('15:45', 'HH:mm').toDate(),
    roomId: 12,
    buildingId: 1,
  },
  {
    id: '13',
    Subject: 'Class',
    StartTime: dayjs('11:30', 'HH:mm').toDate(),
    EndTime: dayjs('12:45', 'HH:mm').toDate(),
    roomId: 13,
    buildingId: 1,
  },
  {
    id: '14',
    Subject: 'Class',
    StartTime: dayjs('13:00', 'HH:mm').toDate(),
    EndTime: dayjs('14:15', 'HH:mm').toDate(),
    roomId: 13,
    buildingId: 1,
  },
  {
    id: '15',
    Subject: 'Class',
    StartTime: dayjs('17:30', 'HH:mm').toDate(),
    EndTime: dayjs('18:45', 'HH:mm').toDate(),
    roomId: 14,
    buildingId: 1,
  },
  {
    id: '16',
    Subject: 'Class',
    StartTime: dayjs('19:00', 'HH:mm').toDate(),
    EndTime: dayjs('21:45', 'HH:mm').toDate(),
    roomId: 14,
    buildingId: 1,
  },
  {
    id: '17',
    Subject: 'Class',
    StartTime: dayjs('08:30', 'HH:mm').toDate(),
    EndTime: dayjs('09:45', 'HH:mm').toDate(),
    roomId: 15,
    buildingId: 1,
  },
  {
    id: '18',
    Subject: 'Class',
    StartTime: dayjs('11:30', 'HH:mm').toDate(),
    EndTime: dayjs('12:45', 'HH:mm').toDate(),
    roomId: 15,
    buildingId: 1,
  },
  {
    id: '19',
    Subject: 'Class',
    StartTime: dayjs('14:30', 'HH:mm').toDate(),
    EndTime: dayjs('15:45', 'HH:mm').toDate(),
    roomId: 16,
    buildingId: 1,
  },
  {
    id: '1',
    Subject: 'Class',
    StartTime: dayjs('08:30', 'HH:mm').toDate(),
    EndTime: dayjs('09:45', 'HH:mm').toDate(),
    roomId: 17,
    buildingId: 1,
  },
  {
    id: '2',
    Subject: 'Class',
    StartTime: dayjs('11:30', 'HH:mm').toDate(),
    EndTime: dayjs('12:45', 'HH:mm').toDate(),
    roomId: 17,
    buildingId: 1,
  },
  {
    id: '3',
    Subject: 'Class',
    StartTime: dayjs('13:00', 'HH:mm').toDate(),
    EndTime: dayjs('14:15', 'HH:mm').toDate(),
    roomId: 17,
    buildingId: 1,
  },
  {
    id: '4',
    Subject: 'Class',
    StartTime: dayjs('16:00', 'HH:mm').toDate(),
    EndTime: dayjs('17:15', 'HH:mm').toDate(),
    roomId: 17,
    buildingId: 1,
  },
  {
    id: '5',
    Subject: 'Class',
    StartTime: dayjs('10:00', 'HH:mm').toDate(),
    EndTime: dayjs('11:15', 'HH:mm').toDate(),
    roomId: 18,
    buildingId: 1,
  },
  {
    id: '6',
    Subject: 'Class',
    StartTime: dayjs('11:30', 'HH:mm').toDate(),
    EndTime: dayjs('12:45', 'HH:mm').toDate(),
    roomId: 18,
    buildingId: 1,
  },
  {
    id: '7',
    Subject: 'Class',
    StartTime: dayjs('19:00', 'HH:mm').toDate(),
    EndTime: dayjs('21:45', 'HH:mm').toDate(),
    roomId: 18,
    buildingId: 1,
  },
  {
    id: '8',
    Subject: 'Class',
    StartTime: dayjs('13:00', 'HH:mm').toDate(),
    EndTime: dayjs('14:15', 'HH:mm').toDate(),
    roomId: 19,
    buildingId: 1,
  },
  {
    id: '9',
    Subject: 'Class',
    StartTime: dayjs('17:30', 'HH:mm').toDate(),
    EndTime: dayjs('18:45', 'HH:mm').toDate(),
    roomId: 19,
    buildingId: 1,
  },
  {
    id: '10',
    Subject: 'Class',
    StartTime: dayjs('08:30', 'HH:mm').toDate(),
    EndTime: dayjs('9:45', 'HH:mm').toDate(),
    roomId: 20,
    buildingId: 1,
  },
  {
    id: '11',
    Subject: 'Class',
    StartTime: dayjs('13:00', 'HH:mm').toDate(),
    EndTime: dayjs('14:15', 'HH:mm').toDate(),
    roomId: 20,
    buildingId: 1,
  },
  {
    id: '12',
    Subject: 'Class',
    StartTime: dayjs('14:30', 'HH:mm').toDate(),
    EndTime: dayjs('15:45', 'HH:mm').toDate(),
    roomId: 20,
    buildingId: 1,
  },
  {
    id: '13',
    Subject: 'Class',
    StartTime: dayjs('11:30', 'HH:mm').toDate(),
    EndTime: dayjs('12:45', 'HH:mm').toDate(),
    roomId: 21,
    buildingId: 1,
  },
  {
    id: '14',
    Subject: 'Class',
    StartTime: dayjs('13:00', 'HH:mm').toDate(),
    EndTime: dayjs('14:15', 'HH:mm').toDate(),
    roomId: 21,
    buildingId: 1,
  },
];
